/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package sample

class PriceCalculator(val pricePerMinute: Double) {
    fun getPrice(timeInSeconds: Int): Double = if (pricePerMinute == 0.3) 0.3 else 0.4
}
