/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package sample

import kotlin.math.roundToInt

class PriceCalculator(rateEurosPerMinute: Double) {
    private var finalPriceMinusDiscount = 1.0
    private var rateDiscount = 0.0
    private val rateCentsPerMinute = rateEurosPerMinute * 100
    private val rate
        get() = rateCentsPerMinute * (1 - rateDiscount)

    fun getPrice(timeInSeconds: Int): Double {
        return if (timeInSeconds < 60) 0.0 else (roundToNextMinute(timeInSeconds) * finalPriceMinusDiscount * rate).roundToInt() / 100.0
    }

    fun setDiscountOnFinalPrice(discountPercentage: Int = 0) {
        finalPriceMinusDiscount = 1 - discountPercentage / 100.0
    }

    fun setDiscountOnRate(discountPercentage: Int) {
        rateDiscount = discountPercentage / 100.0
    }

    private fun roundToNextMinute(timeInSeconds: Int): Int {
        return if (timeInSeconds % 60 == 0) timeInSeconds / 60 else timeInSeconds / 60 + 1
    }
}
