/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package sample

import kotlin.math.roundToInt

class PriceCalculator(pricePerMinuteEuro: Double) {
    private val pricePerMinuteCents = (pricePerMinuteEuro * 100).roundToInt()

    fun getPrice(timeInSeconds: Int): Double = roundToNextMinute(timeInSeconds) * pricePerMinuteCents / 100.0

    private fun roundToNextMinute(timeInSeconds: Int): Int {
        return if (timeInSeconds % 60 == 0) timeInSeconds / 60 else timeInSeconds / 60 + 1
    }
}
