/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package sample

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.CsvSource

class PriceCalculatorTest {
    @ParameterizedTest
    @CsvSource("0.30, 60, 0.30", "0.20, 120, 0.40")
    fun `calculates price with whole minutes`(pricePerMinute: Double, timeInSeconds: Int, expectedPrice: Double) {
        val calculator = PriceCalculator(pricePerMinute)

        assertThat(calculator.getPrice(timeInSeconds)).isEqualTo(expectedPrice)
    }
}
